version: '3.8'

services:
  rag-backend:
    image: prahlad8ac/backend:v1.0.4 
    container_name: rag-backend
    ports:
      - "8000:8000"  
    networks:
      - rag-network

  rag-frontend:
      image: prahlad8ac/frontend:latest
      container_name: rag-frontend
      ports:
        - "80:80"
      networks:
        - rag-network

networks:
  rag-network:
    driver: bridge
